# Generated by Django 5.0.3 on 2024-07-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Javoxir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('malumot1', models.TextField()),
                ('malumot2', models.CharField(max_length=100)),
                ('asosiy_m', models.CharField(max_length=50)),
                ('tugulgan_kun', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sayt', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('rasim', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
