# Generated by Django 5.0.3 on 2024-07-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_javoxir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='javoxir',
            old_name='rasim',
            new_name='rasim1',
        ),
    ]
