# Generated by Django 5.0.3 on 2024-07-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_rasim_javoxir_rasim1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='javoxir',
            old_name='rasim1',
            new_name='rasim',
        ),
    ]
