# Generated by Django 5.0.3 on 2024-07-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_rasim1_javoxir_rasim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baxromjon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('malumot', models.TextField()),
                ('xizmat1', models.TextField()),
                ('xizmat2', models.TextField()),
                ('xizmat3', models.TextField()),
                ('xizmat4', models.TextField()),
                ('xizmat5', models.TextField()),
                ('xizmat6', models.TextField()),
            ],
        ),
    ]
