# Generated by Django 5.0.3 on 2024-07-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_xodimlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axborot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('malumot', models.CharField(max_length=200)),
                ('ism', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=100)),
                ('lavozimi', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
