# Generated by Django 5.0.3 on 2024-07-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_axborot_lavozim_remove_axborot_malumot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='axborot',
            name='rasim',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
