# Generated by Django 5.0.3 on 2024-07-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_axborot_rasim'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Axborot',
            new_name='Raxbarlar',
        ),
    ]
