# Generated by Django 5.0.3 on 2024-07-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_baxromjon_rename_ism_javoxir_ism3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xodimlar',
            old_name='ism2',
            new_name='ism',
        ),
        migrations.RenameField(
            model_name='xodimlar',
            old_name='lavozim',
            new_name='lavozimi',
        ),
        migrations.RenameField(
            model_name='xodimlar',
            old_name='malumot',
            new_name='text',
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='rasim',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
