# Generated by Django 5.0.3 on 2024-07-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_ism2_xodimlar_ism_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('malumot', models.CharField(max_length=100)),
            ],
        ),
    ]
