# Generated by Django 5.0.3 on 2024-07-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_servis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bino', models.CharField(max_length=50)),
                ('xona', models.CharField(max_length=50)),
            ],
        ),
    ]
