# Generated by Django 5.0.3 on 2024-07-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='rasim',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
