# Generated by Django 5.0.3 on 2024-07-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_foto_rasim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='rasim',
            new_name='rsim',
        ),
    ]
