# Generated by Django 5.0.3 on 2024-07-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_rasim_foto_rsim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='rsim',
            new_name='rasim',
        ),
    ]
