# Generated by Django 5.0.3 on 2024-07-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_rsim_foto_rasim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis',
            name='malumot',
            field=models.TextField(),
        ),
    ]
