# Generated by Django 5.0.3 on 2024-07-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_kompyuter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompyuter',
            name='soni',
            field=models.IntegerField(),
        ),
    ]
