# Generated by Django 5.0.3 on 2024-07-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_kompyuter_soni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='javoxir',
            old_name='address',
            new_name='ism',
        ),
        migrations.RenameField(
            model_name='javoxir',
            old_name='asosiy_m',
            new_name='lavozim',
        ),
        migrations.RenameField(
            model_name='javoxir',
            old_name='malumot1',
            new_name='malumot',
        ),
        migrations.RemoveField(
            model_name='javoxir',
            name='ism3',
        ),
        migrations.RemoveField(
            model_name='javoxir',
            name='malumot2',
        ),
        migrations.RemoveField(
            model_name='javoxir',
            name='sayt',
        ),
        migrations.RemoveField(
            model_name='javoxir',
            name='tugulgan_kun',
        ),
    ]
