# Generated by Django 5.0.3 on 2024-07-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_address_javoxir_ism_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Javoxir',
            new_name='Prorektor',
        ),
    ]
