# Generated by Django 5.0.3 on 2024-07-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_javoxir_prorektor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM_raxbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=50)),
                ('malumot', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('rasim', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
