# Generated by Django 5.0.3 on 2024-07-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_atm_raxbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rttm_malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malumot', models.TextField()),
                ('rasim', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Xodimlar',
        ),
    ]
