# Generated by Django 5.0.3 on 2024-07-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rttm_malumot_delete_xodimlar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raxbarlar',
            new_name='Xodimlari',
        ),
    ]
