# Generated by Django 5.0.3 on 2024-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_raxbarlar_xodimlari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adti',
            name='fayl',
            field=models.FileField(upload_to='', verbose_name='fayl'),
        ),
        migrations.AlterField(
            model_name='adti',
            name='malumot',
            field=models.TextField(verbose_name='malumot'),
        ),
        migrations.AlterField(
            model_name='adti',
            name='nomi',
            field=models.CharField(max_length=200, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='adti',
            name='rasm',
            field=models.ImageField(upload_to='media/', verbose_name='rasm'),
        ),
        migrations.AlterField(
            model_name='adti',
            name='yili',
            field=models.CharField(max_length=100, verbose_name='yili'),
        ),
    ]
