# Generated by Django 5.0.7 on 2024-07-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_adti_fayl_alter_adti_malumot_alter_adti_nomi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adti',
            name='malumot_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adti',
            name='malumot_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adti',
            name='malumot_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adti',
            name='nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adti',
            name='nomi_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adti',
            name='nomi_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adti',
            name='fayl',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='adti',
            name='malumot',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adti',
            name='nomi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adti',
            name='rasm',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='adti',
            name='yili',
            field=models.CharField(max_length=100),
        ),
    ]
