# Generated by Django 5.0.7 on 2024-07-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_adti_malumot_en_adti_malumot_ru_adti_malumot_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adti',
            name='yili_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adti',
            name='yili_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adti',
            name='yili_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
