# Generated by Django 5.0.7 on 2024-07-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_adti_yili_en_adti_yili_ru_adti_yili_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adti',
            name='yili_en',
        ),
        migrations.RemoveField(
            model_name='adti',
            name='yili_ru',
        ),
        migrations.RemoveField(
            model_name='adti',
            name='yili_uz',
        ),
    ]
