# Generated by Django 5.0.7 on 2024-07-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_adti_yili_en_remove_adti_yili_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rttm_malumot',
            name='malumot_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rttm_malumot',
            name='malumot_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rttm_malumot',
            name='malumot_uz',
            field=models.TextField(null=True),
        ),
    ]
