# Generated by Django 5.0.7 on 2024-07-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rttm_malumot_malumot_en_rttm_malumot_malumot_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prorektor',
            name='ism_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='ism_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='ism_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='lavozim_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='lavozim_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='lavozim_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='malumot_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='malumot_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='malumot_uz',
            field=models.TextField(null=True),
        ),
    ]
