# Generated by Django 5.0.7 on 2024-07-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_prorektor_ism_en_prorektor_ism_ru_prorektor_ism_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm_raxbar',
            name='lavozim',
        ),
        migrations.RemoveField(
            model_name='prorektor',
            name='ism_en',
        ),
        migrations.RemoveField(
            model_name='prorektor',
            name='ism_ru',
        ),
        migrations.RemoveField(
            model_name='prorektor',
            name='ism_uz',
        ),
        migrations.RemoveField(
            model_name='prorektor',
            name='lavozim_en',
        ),
        migrations.RemoveField(
            model_name='prorektor',
            name='lavozim_ru',
        ),
        migrations.RemoveField(
            model_name='prorektor',
            name='lavozim_uz',
        ),
        migrations.RemoveField(
            model_name='prorektor',
            name='malumot_en',
        ),
        migrations.RemoveField(
            model_name='prorektor',
            name='malumot_ru',
        ),
        migrations.RemoveField(
            model_name='prorektor',
            name='malumot_uz',
        ),
        migrations.RemoveField(
            model_name='rttm_malumot',
            name='malumot_en',
        ),
        migrations.RemoveField(
            model_name='rttm_malumot',
            name='malumot_ru',
        ),
        migrations.RemoveField(
            model_name='rttm_malumot',
            name='malumot_uz',
        ),
    ]
