# Generated by Django 5.0.7 on 2024-07-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_atm_raxbar_lavozim_remove_prorektor_ism_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prorektor',
            name='lavozim',
        ),
    ]
