# Generated by Django 5.0.7 on 2024-07-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_prorektor_lavozim'),
    ]

    operations = [
        migrations.AddField(
            model_name='prorektor',
            name='ism_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='ism_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='ism_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='malumot_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='malumot_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='malumot_uz',
            field=models.TextField(null=True),
        ),
    ]
