# Generated by Django 5.0.7 on 2024-07-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_prorektor_ism_en_prorektor_ism_ru_prorektor_ism_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm_raxbar',
            name='ism_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atm_raxbar',
            name='ism_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atm_raxbar',
            name='ism_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atm_raxbar',
            name='malumot_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='atm_raxbar',
            name='malumot_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='atm_raxbar',
            name='malumot_uz',
            field=models.TextField(null=True),
        ),
    ]
