# Generated by Django 5.0.7 on 2024-07-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_atm_raxbar_ism_en_atm_raxbar_ism_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlari',
            name='ism1_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xodimlari',
            name='ism1_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xodimlari',
            name='ism1_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xodimlari',
            name='lavozimi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xodimlari',
            name='lavozimi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xodimlari',
            name='lavozimi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xodimlari',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xodimlari',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xodimlari',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
