# Generated by Django 5.0.7 on 2024-07-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_adti_yili_en_adti_yili_ru_adti_yili_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='servis',
            name='malumot_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servis',
            name='malumot_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servis',
            name='malumot_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servis',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servis',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servis',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
