# Generated by Django 5.0.7 on 2024-07-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_adti_publish_adti_uplish'),
    ]

    operations = [
        migrations.AddField(
            model_name='rttm_malumot',
            name='malumot_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rttm_malumot',
            name='malumot_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rttm_malumot',
            name='malumot_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rttm_malumot',
            name='rasim_en',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='rttm_malumot',
            name='rasim_ru',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='rttm_malumot',
            name='rasim_uz',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
