# Generated by Django 5.0.7 on 2024-07-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rttm_malumot_malumot_en_rttm_malumot_malumot_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompyuter',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kompyuter',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kompyuter',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kompyuter',
            name='soni_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kompyuter',
            name='soni_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kompyuter',
            name='soni_uz',
            field=models.IntegerField(null=True),
        ),
    ]
