# Generated by Django 5.0.7 on 2024-07-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_kompyuter_nomi_en_kompyuter_nomi_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavozim_nomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim_nomi', models.CharField(max_length=100)),
                ('lavozim_nomi_en', models.CharField(max_length=100, null=True)),
                ('lavozim_nomi_ru', models.CharField(max_length=100, null=True)),
                ('lavozim_nomi_uz', models.CharField(max_length=100, null=True)),
                ('ism', models.CharField(max_length=1)),
                ('ism_en', models.CharField(max_length=1, null=True)),
                ('ism_ru', models.CharField(max_length=1, null=True)),
                ('ism_uz', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
