# Generated by Django 5.0.7 on 2024-07-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_lavozim_nomi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lavozim_nomi',
        ),
        migrations.AddField(
            model_name='atm_raxbar',
            name='lavozim_nomi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prorektor',
            name='lavozim_nomi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
