# Generated by Django 5.0.7 on 2024-07-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_delete_lavozim_nomi_atm_raxbar_lavozim_nomi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm_raxbar',
            name='lavozim_nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atm_raxbar',
            name='lavozim_nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atm_raxbar',
            name='lavozim_nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='lavozim_nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='lavozim_nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prorektor',
            name='lavozim_nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
